### ISSUE TITLE
Missing argument in hook_fn in model_profile.py

### ISSUE THREAD

**Issue by llgelarall** [RuokaiYin/LoAS#1]
Hi,

I noticed a small issue in the file model_profile.py on line 67. The hook_fn function appears to be missing an argument, which prevents the code from executing correctly. Specifically, it seems the function should include the n_layer and args parameters when registering the hook.

`hook = module.register_forward_hook(hook_fn(n_layer, args))`

**Comment by RuokaiYin** [comment]
Thank you for pointing out this issue! You are correct that the ‘args’ argument was missing in model_profile.py.

The reason for this oversight is that I moved the hook_fn (originally located within model_profile) into the shared utility file. To access the global timestep, I subsequently passed the ‘args’ into the hook function. Unfortunately, I forgot to update model_profile.py accordingly.

I have updated the codes. Thanks again for bringing this to my attention!
